const geoJSONDataWithoutGeometry = [
  {
    type: "FeatureCollection",
    name: "Mijen's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010002",
          village: "Bubakan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010001",
          village: "Cangkiran",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010009",
          village: "Jatibarang",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010007",
          village: "Jatisari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010003",
          village: "Karangmalang",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010010",
          village: "Kedungpani",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010008",
          village: "Mijen",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010012",
          village: "Ngadirgo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010011",
          village: "Pesantren",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010004",
          village: "Polaman",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010005",
          village: "Purwosari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010006",
          village: "Tambangan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010013",
          village: "Wonolopo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374010",
          district: "Mijen",
          village_code: "id3374010014",
          village: "Wonoplumbon",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Gunung Pati's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020009",
          village: "Cepoko",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020001",
          village: "Gunungpati",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020010",
          village: "Jatirejo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020013",
          village: "Kalisegoro",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020011",
          village: "Kandri",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020005",
          village: "Mangunsari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020007",
          village: "Ngijo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020008",
          village: "Nongkosawit",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020004",
          village: "Pakintelan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020006",
          village: "Patemon",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020002",
          village: "Plalangan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020012",
          village: "Pungangan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020016",
          village: "Sadeng",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020014",
          village: "Sekaran",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020015",
          village: "Sukorejo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374020",
          district: "Gunung Pati",
          village_code: "id3374020003",
          village: "Sumurejo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Banyumanik's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374030",
          district: "Banyumanik",
          village_code: "id3374030005",
          village: "Banyumanik",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374030",
          district: "Banyumanik",
          village_code: "id3374030002",
          village: "Gedawang",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374030",
          district: "Banyumanik",
          village_code: "id3374030003",
          village: "Jabungan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374030",
          district: "Banyumanik",
          village_code: "id3374030011",
          village: "Ngesrep",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374030",
          district: "Banyumanik",
          village_code: "id3374030004",
          village: "Padangsari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374030",
          district: "Banyumanik",
          village_code: "id3374030007",
          village: "Pedalangan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374030",
          district: "Banyumanik",
          village_code: "id3374030001",
          village: "Pudakpayung",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374030",
          district: "Banyumanik",
          village_code: "id3374030009",
          village: "Srondol Kulon",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374030",
          district: "Banyumanik",
          village_code: "id3374030006",
          village: "Srondol Wetan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374030",
          district: "Banyumanik",
          village_code: "id3374030008",
          village: "Sumurboto",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374030",
          district: "Banyumanik",
          village_code: "id3374030010",
          village: "Tinjomoyo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Gajah Mungkur's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374040",
          district: "Gajah Mungkur",
          village_code: "id3374040002",
          village: "Bendan Duwur",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374040",
          district: "Gajah Mungkur",
          village_code: "id3374040005",
          village: "Bendan Ngisor",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374040",
          district: "Gajah Mungkur",
          village_code: "id3374040007",
          village: "Bendungan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374040",
          district: "Gajah Mungkur",
          village_code: "id3374040004",
          village: "Gajahmungkur",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374040",
          district: "Gajah Mungkur",
          village_code: "id3374040003",
          village: "Karang Rejo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374040",
          district: "Gajah Mungkur",
          village_code: "id3374040008",
          village: "Lempongsari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374040",
          district: "Gajah Mungkur",
          village_code: "id3374040006",
          village: "Petompon",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374040",
          district: "Gajah Mungkur",
          village_code: "id3374040001",
          village: "Sampangan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Semarang Selatan's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374050",
          district: "Semarang Selatan",
          village_code: "id3374050002",
          village: "Barusari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374050",
          district: "Semarang Selatan",
          village_code: "id3374050001",
          village: "Bulustalan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374050",
          district: "Semarang Selatan",
          village_code: "id3374050008",
          village: "Lamper Kidul",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374050",
          district: "Semarang Selatan",
          village_code: "id3374050009",
          village: "Lamper Lor",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374050",
          district: "Semarang Selatan",
          village_code: "id3374050010",
          village: "Lamper Tengah",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374050",
          district: "Semarang Selatan",
          village_code: "id3374050004",
          village: "Mugassari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374050",
          district: "Semarang Selatan",
          village_code: "id3374050007",
          village: "Peterongan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374050",
          district: "Semarang Selatan",
          village_code: "id3374050005",
          village: "Pleburan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374050",
          district: "Semarang Selatan",
          village_code: "id3374050003",
          village: "Randusari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374050",
          district: "Semarang Selatan",
          village_code: "id3374050006",
          village: "Wonodri",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Candisari's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374060",
          district: "Candisari",
          village_code: "id3374060004",
          village: "Candi",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374060",
          district: "Candisari",
          village_code: "id3374060001",
          village: "Jatingaleh",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374060",
          district: "Candisari",
          village_code: "id3374060003",
          village: "Jomblang",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374060",
          district: "Candisari",
          village_code: "id3374060005",
          village: "Kaliwiru",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374060",
          district: "Candisari",
          village_code: "id3374060002",
          village: "Karanganyar Gunung",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374060",
          district: "Candisari",
          village_code: "id3374060007",
          village: "Tegalsari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374060",
          district: "Candisari",
          village_code: "id3374060006",
          village: "Wonotingal",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Tembalang's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374070",
          district: "Tembalang",
          village_code: "id3374070005",
          village: "Bulusan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374070",
          district: "Tembalang",
          village_code: "id3374070009",
          village: "Jangli",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374070",
          district: "Tembalang",
          village_code: "id3374070011",
          village: "Kedungmundu",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374070",
          district: "Tembalang",
          village_code: "id3374070003",
          village: "Kramas",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374070",
          district: "Tembalang",
          village_code: "id3374070006",
          village: "Mangunharjo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374070",
          district: "Tembalang",
          village_code: "id3374070002",
          village: "Meteseh",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374070",
          district: "Tembalang",
          village_code: "id3374070001",
          village: "Rowosari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374070",
          district: "Tembalang",
          village_code: "id3374070008",
          village: "Sambiroto",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374070",
          district: "Tembalang",
          village_code: "id3374070012",
          village: "Sendangguwo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374070",
          district: "Tembalang",
          village_code: "id3374070007",
          village: "Sendangmulyo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374070",
          district: "Tembalang",
          village_code: "id3374070010",
          village: "Tandang",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374070",
          district: "Tembalang",
          village_code: "id3374070004",
          village: "Tembalang",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Pedurungan's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374080",
          district: "Pedurungan",
          village_code: "id3374080001",
          village: "Gemah",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374080",
          district: "Pedurungan",
          village_code: "id3374080009",
          village: "Kalicari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374080",
          district: "Pedurungan",
          village_code: "id3374080012",
          village: "Muktiharjo Kidul",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374080",
          district: "Pedurungan",
          village_code: "id3374080008",
          village: "Palebon",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374080",
          district: "Pedurungan",
          village_code: "id3374080002",
          village: "Pedurungan Kidul",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374080",
          district: "Pedurungan",
          village_code: "id3374080005",
          village: "Pedurungan Lor",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374080",
          district: "Pedurungan",
          village_code: "id3374080007",
          village: "Pedurungan Tengah",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374080",
          district: "Pedurungan",
          village_code: "id3374080004",
          village: "Penggaron Kidul",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374080",
          district: "Pedurungan",
          village_code: "id3374080003",
          village: "Plamongan Sari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374080",
          district: "Pedurungan",
          village_code: "id3374080006",
          village: "Tlogomulyo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374080",
          district: "Pedurungan",
          village_code: "id3374080010",
          village: "Tlogosari Kulon",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374080",
          district: "Pedurungan",
          village_code: "id3374080011",
          village: "Tlogosari Wetan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Genuk's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090004",
          village: "Bangetayu Kulon",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090005",
          village: "Bangetayu Wetan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090010",
          village: "Banjardowo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090002",
          village: "Gebangsari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090003",
          village: "Genuksari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090009",
          village: "Karangroto",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090008",
          village: "Kudu",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090001",
          village: "Muktiharjo Lor",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090007",
          village: "Penggaron Lor",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090006",
          village: "Sembungharjo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090013",
          village: "Terboyo Kulon",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090012",
          village: "Terboyo Wetan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374090",
          district: "Genuk",
          village_code: "id3374090011",
          village: "Trimulyo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Gayamsari's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374100",
          district: "Gayamsari",
          village_code: "id3374100002",
          village: "Gayamsari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374100",
          district: "Gayamsari",
          village_code: "id3374100006",
          village: "Kaligawe",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374100",
          district: "Gayamsari",
          village_code: "id3374100001",
          village: "Pandean Lamper",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374100",
          district: "Gayamsari",
          village_code: "id3374100004",
          village: "Sambirejo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374100",
          district: "Gayamsari",
          village_code: "id3374100005",
          village: "Sawahbesar",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374100",
          district: "Gayamsari",
          village_code: "id3374100003",
          village: "Siwalan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374100",
          district: "Gayamsari",
          village_code: "id3374100007",
          village: "Tambakrejo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Semarang Timur's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374110",
          district: "Semarang Timur",
          village_code: "id3374110006",
          village: "Bugangan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374110",
          district: "Semarang Timur",
          village_code: "id3374110002",
          village: "Karangtempel",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374110",
          district: "Semarang Timur",
          village_code: "id3374110001",
          village: "Karangturi",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374110",
          district: "Semarang Timur",
          village_code: "id3374110005",
          village: "Kebonagung",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374110",
          district: "Semarang Timur",
          village_code: "id3374110010",
          village: "Kemijen",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374110",
          district: "Semarang Timur",
          village_code: "id3374110008",
          village: "Mlatibaru",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374110",
          district: "Semarang Timur",
          village_code: "id3374110007",
          village: "Mlatiharjo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374110",
          district: "Semarang Timur",
          village_code: "id3374110009",
          village: "Rejomulyo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374110",
          district: "Semarang Timur",
          village_code: "id3374110003",
          village: "Rejosari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374110",
          district: "Semarang Timur",
          village_code: "id3374110004",
          village: "Sarirejo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Semarang Utara's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374120",
          district: "Semarang Utara",
          village_code: "id3374120008",
          village: "Bandarharjo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374120",
          district: "Semarang Utara",
          village_code: "id3374120001",
          village: "Bulu Lor",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374120",
          district: "Semarang Utara",
          village_code: "id3374120007",
          village: "Dadapsari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374120",
          district: "Semarang Utara",
          village_code: "id3374120005",
          village: "Kuningan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374120",
          district: "Semarang Utara",
          village_code: "id3374120003",
          village: "Panggung Kidul",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374120",
          district: "Semarang Utara",
          village_code: "id3374120004",
          village: "Panggung Lor",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374120",
          district: "Semarang Utara",
          village_code: "id3374120002",
          village: "Plombokan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374120",
          district: "Semarang Utara",
          village_code: "id3374120006",
          village: "Purwosari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374120",
          district: "Semarang Utara",
          village_code: "id3374120009",
          village: "Tanjungmas",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Semarang Tengah's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130010",
          village: "Bangunharjo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130004",
          village: "Brumbungan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130006",
          village: "Gabahan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130003",
          village: "Jagalan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130002",
          village: "Karangkidul",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130009",
          village: "Kauman",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130011",
          village: "Kembangsari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130007",
          village: "Kranggan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130005",
          village: "Miroto",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130012",
          village: "Pandansari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130001",
          village: "Pekunden",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130014",
          village: "Pendrikan Kidul",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130015",
          village: "Pendrikan Lor",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130008",
          village: "Purwodinatan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374130",
          district: "Semarang Tengah",
          village_code: "id3374130013",
          village: "Sekayu",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Semarang Barat's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140005",
          village: "Bojongsalaman",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140004",
          village: "Bongsari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140006",
          village: "Cabean",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140008",
          village: "Gisikdrono",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140009",
          village: "Kalibanteng Kidul",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140010",
          village: "Kalibanteng Kulon",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140014",
          village: "Karang Ayu",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140001",
          village: "Kembangarum",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140011",
          village: "Krapyak",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140015",
          village: "Krobokan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140002",
          village: "Manyaran",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140003",
          village: "Ngemplaksimongan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140007",
          village: "Salamanmloyo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140012",
          village: "Tambak Harjo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140016",
          village: "Tawangmas",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374140",
          district: "Semarang Barat",
          village_code: "id3374140013",
          village: "Tawangsari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Tugu's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374150",
          district: "Tugu",
          village_code: "id3374150001",
          village: "Jerakah",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374150",
          district: "Tugu",
          village_code: "id3374150003",
          village: "Karanganyar",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374150",
          district: "Tugu",
          village_code: "id3374150007",
          village: "Mangkang Kulon",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374150",
          district: "Tugu",
          village_code: "id3374150005",
          village: "Mangkang Wetan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374150",
          district: "Tugu",
          village_code: "id3374150006",
          village: "Mangunharjo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374150",
          district: "Tugu",
          village_code: "id3374150004",
          village: "Randu Garut",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374150",
          district: "Tugu",
          village_code: "id3374150002",
          village: "Tugurejo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
  {
    type: "FeatureCollection",
    name: "Ngaliyan's Village",
    crs: {
      type: "name",
      properties: {
        name: "urn:ogc:def:crs:OGC:1.3:CRS84",
      },
    },
    features: [
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374160",
          district: "Ngaliyan",
          village_code: "id3374160005",
          village: "Bambankerep",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374160",
          district: "Ngaliyan",
          village_code: "id3374160003",
          village: "Bringin",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374160",
          district: "Ngaliyan",
          village_code: "id3374160009",
          village: "Gondoriyo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374160",
          district: "Ngaliyan",
          village_code: "id3374160006",
          village: "Kalipancur",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374160",
          district: "Ngaliyan",
          village_code: "id3374160004",
          village: "Ngaliyan",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374160",
          district: "Ngaliyan",
          village_code: "id3374160001",
          village: "Podorejo",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374160",
          district: "Ngaliyan",
          village_code: "id3374160007",
          village: "Purwoyoso",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374160",
          district: "Ngaliyan",
          village_code: "id3374160008",
          village: "Tambakaji",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374160",
          district: "Ngaliyan",
          village_code: "id3374160002",
          village: "Wates",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
      {
        type: "Feature",
        properties: {
          country_code: "id",
          country: "Indonesia",
          province_code: "id33",
          province: "Jawa Tengah",
          regency_code: "id3374",
          regency: "Kota Semarang",
          district_code: "id3374160",
          district: "Ngaliyan",
          village_code: "id3374160010",
          village: "Wonosari",
          source: "HDX-BPS-2020",
          date: "2019-12-20",
          valid_on: "2020-04-01",
        },
      },
    ],
  },
];

export default geoJSONDataWithoutGeometry;
